table merged_cm_jobs
	lineageTag: cc8e0fff-0564-469f-ba1c-521497bab35b

	measure count_regions = COUNT(merged_cm_jobs[region])
		formatString: 0
		lineageTag: fa2c6b52-864d-400e-a029-0e7380bc1fa4

	measure count_jobs = COUNT(merged_cm_jobs[poste])
		formatString: 0
		lineageTag: 9fcdaebf-92e8-4f1c-9f32-4dc6493d7bb1

	column poste
		dataType: string
		lineageTag: a7b71a44-f084-495e-b088-4cea3e76af9c
		summarizeBy: none
		sourceColumn: poste

		annotation SummarizationSetBy = Automatic

	column localité
		dataType: string
		lineageTag: 24f70122-d7bd-488a-8fc6-b7bb351ba039
		summarizeBy: none
		sourceColumn: localité

		annotation SummarizationSetBy = Automatic

	column organisation
		dataType: string
		lineageTag: 7ce92ff4-1926-4d19-bc5a-19953b10fc71
		summarizeBy: none
		sourceColumn: organisation

		annotation SummarizationSetBy = Automatic

	column 'date de publication'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 69bb36a2-618c-4b28-a71c-08ffc1827947
		summarizeBy: none
		sourceColumn: date de publication

		variation Variation
			isDefault
			relationship: d694eb3c-63b4-4e09-a381-723a6a267157
			defaultHierarchy: LocalDateTable_179d40f8-346b-420c-9177-36a8c941aa0b.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column études
		dataType: string
		lineageTag: b13b6141-ec92-427e-8afc-575b0fec6516
		summarizeBy: none
		sourceColumn: études

		annotation SummarizationSetBy = Automatic

	column expérience
		dataType: string
		lineageTag: cc1417de-5336-4fac-9921-0a7cc3e0a961
		summarizeBy: none
		sourceColumn: expérience

		annotation SummarizationSetBy = Automatic

	column compétence
		dataType: string
		lineageTag: 48014cfd-22aa-4632-885a-77b253713bbc
		summarizeBy: none
		sourceColumn: compétence

		annotation SummarizationSetBy = Automatic

	column contrat
		dataType: string
		lineageTag: ea0b168a-ae88-44f9-9ae5-f50faae82abe
		summarizeBy: none
		sourceColumn: contrat

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: dd4655c6-851c-46d2-ae32-eb3e21ead10a
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column salaire
		dataType: string
		lineageTag: 03950c3e-1e78-4527-9432-98b154f5c7af
		summarizeBy: none
		sourceColumn: salaire

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		lineageTag: 4a4181ed-8be0-4ca4-9dc9-c01e35fc8288
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column 'lien offre'
		dataType: string
		lineageTag: d6bcec15-9d1e-4c3a-8935-f7d4bca76a4e
		summarizeBy: none
		sourceColumn: lien offre

		annotation SummarizationSetBy = Automatic

	partition merged_cm_jobs = m
		mode: import
		source = ```
				let
				    Source = Csv.Document(File.Contents(CheminProjet & "\data\merged_cm_jobs.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"poste", type text}, {"localité", type text}, {"organisation", type text}, {"date de publication", type date}, {"études", type text}, {"expérience", type text}, {"compétence", type text}, {"contrat", type text}, {"region", type text}, {"salaire", type text}, {"source", type text}, {"lien offre", type text}}),
				    #"Fractionner la colonne par délimiteur" = Table.ExpandListColumn(Table.TransformColumns(#"Type modifié", {{"region", Splitter.SplitTextByDelimiter("&", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "region"),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Fractionner la colonne par délimiteur",{{"region", type text}}),
				    #"Valeur remplacée" = Table.ReplaceValue(#"Type modifié1","Emploi-international","International",Replacer.ReplaceText,{"region"}),
				    #"Espaces supprimés" = Table.TransformColumns(#"Valeur remplacée",{{"region", Text.Trim, type text}}),
				    #"Valeur remplacée1" = Table.ReplaceValue(#"Espaces supprimés","Adamoua","Adamaoua",Replacer.ReplaceText,{"region"}),
				    #"Valeur remplacée2" = Table.ReplaceValue(#"Valeur remplacée1","...","Tout_le_cameroun",Replacer.ReplaceText,{"region"}),
				    #"Espaces supprimés1" = Table.TransformColumns(#"Valeur remplacée2",{{"contrat", Text.Trim, type text}, {"poste", Text.Trim, type text}, {"localité", Text.Trim, type text}, {"organisation", Text.Trim, type text}, {"études", Text.Trim, type text}, {"expérience", Text.Trim, type text}, {"compétence", Text.Trim, type text}}),
				    #"Espaces supprimés2" = Table.TransformColumns(#"Espaces supprimés1",{{"contrat", Text.Trim, type text}, {"region", Text.Trim, type text}, {"salaire", Text.Trim, type text}, {"source", Text.Trim, type text}, {"lien offre", Text.Trim, type text}}),
				    #"Valeur remplacée3" = Table.ReplaceValue(#"Espaces supprimés2","Tout-le-cameroun","Tout_le_cameroun",Replacer.ReplaceText,{"region"}),
				    #"Valeur remplacée4" = Table.ReplaceValue(#"Valeur remplacée3","Responsable commercial","Commercial",Replacer.ReplaceText,{"poste"}),
				    #"Valeur remplacée5" = Table.ReplaceValue(#"Valeur remplacée4","Commercial(e)","Commercial",Replacer.ReplaceText,{"poste"}),
				    #"Valeur remplacée6" = Table.ReplaceValue(#"Valeur remplacée5","Comptables","Comptable",Replacer.ReplaceText,{"poste"}),
				    #"Valeur remplacée7" = Table.ReplaceValue(#"Valeur remplacée6","Chauffeur professionnel","Chauffeur",Replacer.ReplaceText,{"poste"}),
				    #"Valeur remplacée8" = Table.ReplaceValue(#"Valeur remplacée7","02 chauffeurs","Chauffeur",Replacer.ReplaceText,{"poste"}),
				    #"Valeur remplacée9" = Table.ReplaceValue(#"Valeur remplacée8","03 chauffeurs","Chauffeur",Replacer.ReplaceText,{"poste"}),
				    #"Valeur remplacée10" = Table.ReplaceValue(#"Valeur remplacée9","Chauffeur - livreur","Chauffeur",Replacer.ReplaceText,{"poste"}),
				    #"Valeur remplacée11" = Table.ReplaceValue(#"Valeur remplacée10","Chauffeur / livreur","Livreur",Replacer.ReplaceText,{"poste"}),
				    #"Transformation en Livreur 1" = Table.ReplaceValue(
				    #"Valeur remplacée11",
				    each[poste],
				    each if Text.Contains([poste], "Chauffeur", Comparer.OrdinalIgnoreCase)
				         and Text.Contains([poste], "livreur", Comparer.OrdinalIgnoreCase)
				         then "Livreur"  else [poste],
				         Replacer.ReplaceValue,
				         {"poste"}
				    ),
				    
				    Normalisation_Chauffeur_1 = Table.ReplaceValue(
				        #"Transformation en Livreur 1",
				        each [poste],
				        each if Text.Contains([poste], "Avis de recrutement des chauffeurs", Comparer.OrdinalIgnoreCase)
				            then "Chauffeur"
				            else [poste],
				        Replacer.ReplaceValue,
				        {"poste"}
				        ),
				    #"Espaces supprimés3" = Table.TransformColumns(Normalisation_Chauffeur_1,{{"poste", Text.Trim, type text}}),
				    #"Valeur remplacée12" = Table.ReplaceValue(#"Espaces supprimés3","Emploi-international","International",Replacer.ReplaceText,{"localité"}),
				    #"Normalisation_coursier" = Table.TransformColumns(
				        #"Valeur remplacée12",
				        {{"poste", each fn_normalize_job_1(_, {"coursier"}, "Coursier", true)}}
				     ),
				    #"Fractionner la colonne par délimiteur1" = Table.ExpandListColumn(Table.TransformColumns(Normalisation_coursier, {{"poste", Splitter.SplitTextByDelimiter(",", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "poste"),
				    #"Type modifié2" = Table.TransformColumnTypes(#"Fractionner la colonne par délimiteur1",{{"poste", type text}}),
				    #"Fractionner la colonne par délimiteur2" = Table.ExpandListColumn(Table.TransformColumns(#"Type modifié2", {{"poste", Splitter.SplitTextByDelimiter(" et ", QuoteStyle.Csv), let itemType = (type nullable text) meta [Serialized.Text = true] in type {itemType}}}), "poste"),
				    #"Type modifié3" = Table.TransformColumnTypes(#"Fractionner la colonne par délimiteur2",{{"poste", type text}}),
				    // #"Doublons supprimés" = Table.Distinct(#"Type modifié3", {"poste"}),
				    #"Normalisation_Stagiaire" = Table.TransformColumns(#"Type modifié3", {{"poste", each fn_normalize_job_1(_, {"stagiaire"}, "Stagiaire", true)}}),
				    #"Normalisation_Secrétaire" = Table.TransformColumns(#"Normalisation_Stagiaire", {{"poste", each fn_normalize_job_1(_, {"secr", "sécr"}, "Secrétaire", false)}}),
				    #"Normalisation_Comptable" = Table.TransformColumns(#"Normalisation_Secrétaire", {{"poste", each fn_normalize_job_1(_, {"comptable"}, "Comptable", true)}}),
				    #"Normalisation_Chauffeur" = Table.TransformColumns(#"Normalisation_Comptable", {{"poste", each fn_normalize_job_1(_, {"chauffeur"}, "Chauffeur", true)}}),
				    #"Normalisation_Commercial" = Table.TransformColumns(#"Normalisation_Chauffeur", {{"poste", each fn_normalize_job_1(_, {"commerc"}, "Commercial", true)}}),
				    #"Normalisation_Responsable_Marketing" = Table.TransformColumns(#"Normalisation_Commercial", {{"poste", each fn_normalize_job_1(_, {"marketing"}, "Responsable marketing", true)}}),
				    #"Normalisation_Assistant_direction" = Table.TransformColumns(#"Normalisation_Responsable_Marketing", {{"poste", each fn_normalize_job_1(_, {"assistant", "dir"}, "Assistant(e) de direction", true)}}),
				    #"Normalisation_Cuisinier" = Table.TransformColumns(#"Normalisation_Assistant_direction", {{"poste", each fn_normalize_job_1(_, {"cuisin"}, "Cuisinier", true)}}),
				    #"Normalisation_Designer" = Table.TransformColumns(#"Normalisation_Cuisinier", {{"poste", each fn_normalize_job_1(_, {"design"}, "Designer graphique", true)}}),
				    #"Normalisation_Développeur_web_1" = Table.TransformColumns(#"Normalisation_Designer", {{"poste", each fn_normalize_job_1(_, {"dev", "web"}, "Développeur web", true)}}),
				    #"Normalisation_Développeur_web_2" = Table.TransformColumns(#"Normalisation_Développeur_web_1", {{"poste", each fn_normalize_job_1(_, {"dév", "web"}, "Développeur web", true)}}),
				    #"Normalisation_Commercial_2" = Table.TransformColumns(#"Normalisation_Développeur_web_2", {{"poste", each fn_normalize_job_1(_, {"agent", "vente"}, "Commercial", true)}}),
				    #"Normalisation_Assistant(e)_direction_2" = Table.TransformColumns(#"Normalisation_Commercial_2", {{"poste", each fn_normalize_job_1(_, {"assistant"}, "Assistant(e) de direction", true)}}),
				    #"Normalisation_Comptable_3" = Table.TransformColumns(#"Normalisation_Assistant(e)_direction_2", {{"poste", each fn_normalize_job_1(_, {"accountant"}, "Comptable", true)}}),
				    #"Normalisation_Commercial_3" = Table.TransformColumns(#"Normalisation_Comptable_3", {{"poste", each fn_normalize_job_1(_, {"vend"}, "Commercial", true)}}),
				    #"Normalisation_Poste_disponible" = Table.TransformColumns(#"Normalisation_Commercial_3", {{"poste", each fn_normalize_job_1(_, {"poste", "non précisé"}, "Poste disponible", false)}}),
				    #"Normalisation_Journaliste_1" = Table.TransformColumns(#"Normalisation_Poste_disponible", {{"poste", each fn_normalize_job_1(_, {"journal"}, "Journaliste tv/web", true)}}),
				    #"Normalisation_Consultant_1" = Table.TransformColumns(#"Normalisation_Journaliste_1", {{"poste", each fn_normalize_job_1(_, {"consult"}, "Consultant", true)}}),
				    #"Normalisation_Business_developer" = Table.TransformColumns(#"Normalisation_Consultant_1", {{"poste", each fn_normalize_job_1(_, {"dev", "busi"}, "Business developer", true)}}),
				    #"Normalisation_Gestionnaire_projet" = Table.TransformColumns(#"Normalisation_Business_developer", {{"poste", each fn_normalize_job_1(_, {"manager"}, "Gestionnaire de projet", true)}}),
				    #"Normalisation_Officier_suivi" = Table.TransformColumns(#"Normalisation_Gestionnaire_projet", {{"poste", each fn_normalize_job_1(_, {"officier"}, "Officier de suivi", true)}}),
				    #"Normalisation_Créateur_contenu" = Table.TransformColumns(#"Normalisation_Officier_suivi", {{"poste", each fn_normalize_job_1(_, {"contenu"}, "Créateur(trice) de contenu", true)}}),
				    #"Normalisation_Chef_agence" = Table.TransformColumns(#"Normalisation_Créateur_contenu", {{"poste", each fn_normalize_job_1(_, {"agence"}, "Chef d'agence", true)}}),
				    #"Espaces supprimés4" = Table.TransformColumns(Normalisation_Chef_agence,{{"poste", Text.Trim, type text}}),
				    #"Erreurs supprimées" = Table.RemoveRowsWithErrors(#"Espaces supprimés4", {"poste"}),
				    #"Lignes filtrées" = Table.SelectRows(#"Erreurs supprimées", each ([poste] <> "" and [poste] <> "/ ou certifiantes﻿" and [poste] <> "b (h/f)" and [poste] <> "bertoua" and [poste] <> "d-1" and [poste] <> "douala" and [poste] <> "garoua" and [poste] <> "garoua." and [poste] <> "la formation" and [poste] <> "Ll" and [poste] <> "maroua" and [poste] <> "yaounde" and [poste] <> "yaoundé")),
				    #"Normalisation_Médecin" = Table.TransformColumns(#"Lignes filtrées", {{"poste", each fn_normalize_job_1(_, {"medecin", "médecin", "médécin"}, "Médecin", false)}}),
				    #"Normalisation_Boulanger" = Table.TransformColumns(#"Normalisation_Médecin", {{"poste", each fn_normalize_job_1(_, {"boulanger"}, "Boulanger", true)}}),
				    #"Retrait_nombres" = Table.TransformColumns(#"Normalisation_Boulanger", {{"poste", each Text.Remove(_, {"0".."9"})}}),
				    #"Espaces supprimés5" = Table.TransformColumns(Retrait_nombres,{{"poste", Text.Trim, type text}}),
				    #"Lignes triées" = Table.Sort(#"Espaces supprimés5",{{"poste", Order.Ascending}}),
				    #"Premières lignes supprimées" = Table.Skip(#"Lignes triées",23),
				    #"Valeur remplacée13" = Table.ReplaceValue(#"Premières lignes supprimées","Administrateur de base de donnees (dba)","Administrateur de base de donnees",Replacer.ReplaceText,{"poste"}),
				    #"Valeur remplacée14" = Table.ReplaceValue(#"Valeur remplacée13","Agent de caisse / caissière","Agent de caisse",Replacer.ReplaceText,{"poste"}),
				    #"Normalisation_Admin_db" = Table.TransformColumns(#"Valeur remplacée14", {{"poste", each fn_normalize_job_1(_, {"base de donnée", "base de donnee", "bases de donnée", "bases de donnee"}, "Administrateur de base de données", false)}}),
				    #"Nettoyage_HF" = Table.ReplaceValue(#"Normalisation_Admin_db", "(h/f)", "", Replacer.ReplaceText, {"poste"}),
				    #"Nettoyage_HF_2" = Table.ReplaceValue(#"Nettoyage_HF", "h/f", "", Replacer.ReplaceText, {"poste"}),
				    #"Remove_chars" = Table.TransformColumns(#"Nettoyage_HF_2", {
				        {"poste", each if _ <> null then Text.Trim(Text.Remove(_, {"0".."9", "!", ".", "?", "*", "=", "+", "."})) else _}
				        }),
				    #"Nettoyage_MF" = Table.ReplaceValue(#"Remove_chars", "(m/f)", "", Replacer.ReplaceText, {"poste"}),
				    #"Nettoyage_MF_2" = Table.ReplaceValue(#"Nettoyage_MF", "m/f", "", Replacer.ReplaceText, {"poste"}),
				    #"Lignes filtrées1" = Table.SelectRows(Nettoyage_MF_2, each true),
				    #"Lignes triées1" = Table.Sort(#"Lignes filtrées1",{{"poste", Order.Ascending}}) 
				in
				    #"Lignes triées1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

