table merged_cm_jobs
	lineageTag: cc8e0fff-0564-469f-ba1c-521497bab35b

	measure Postes/Region = COUNT(merged_cm_jobs[region])
		formatString: 0
		lineageTag: fa2c6b52-864d-400e-a029-0e7380bc1fa4

	measure 'Nombre de postes' = COUNT(merged_cm_jobs[poste])
		formatString: 0
		lineageTag: 9fcdaebf-92e8-4f1c-9f32-4dc6493d7bb1

	measure count_distinct_region = DISTINCTCOUNT(merged_cm_jobs[region])
		formatString: 0
		lineageTag: 4f9b316c-709e-4f7f-97b9-e80e7fa26c7b

	measure count_distinct_companies = DISTINCTCOUNT(merged_cm_jobs[organisation])
		formatString: 0
		lineageTag: 0ac9400b-7ead-4fac-ae52-ad81b16f2e52

	measure count_compétences = COUNT(merged_cm_jobs[compétence])
		formatString: 0
		lineageTag: 0bc3c134-9532-4627-a37c-103d5255b8dd

	measure count_etudes = COUNT(merged_cm_jobs[études])
		formatString: 0
		lineageTag: 2549c6db-19ad-4308-a88b-29561c5b88a0

	measure count_companies = COUNT(merged_cm_jobs[organisation])
		formatString: 0
		lineageTag: 33920fd3-5b21-4877-8f61-1ca60af07663

	measure nb_years = DISTINCTCOUNT(merged_cm_jobs[Année])
		formatString: 0
		lineageTag: af9531e5-e687-40db-95e1-5ecfb13f43ca

	measure count_metiers = DISTINCTCOUNT(merged_cm_jobs[poste])
		formatString: 0
		lineageTag: be4bbca3-469a-4a08-92e4-25644f479672

	measure count_contrat = COUNT(merged_cm_jobs[contrat])
		formatString: 0
		lineageTag: 87a18451-efc3-4395-b62d-2e0e320bdfcf

	measure count_localité = COUNT(merged_cm_jobs[localité])
		formatString: 0
		lineageTag: 57d810aa-0092-4bb5-a3a6-6d550360c9d1

	column poste
		dataType: string
		lineageTag: a7b71a44-f084-495e-b088-4cea3e76af9c
		summarizeBy: none
		sourceColumn: poste

		annotation SummarizationSetBy = Automatic

	column localité
		dataType: string
		lineageTag: 24f70122-d7bd-488a-8fc6-b7bb351ba039
		summarizeBy: none
		sourceColumn: localité

		annotation SummarizationSetBy = Automatic

	column organisation
		dataType: string
		lineageTag: 7ce92ff4-1926-4d19-bc5a-19953b10fc71
		summarizeBy: none
		sourceColumn: organisation

		annotation SummarizationSetBy = Automatic

	column 'date de publication'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 69bb36a2-618c-4b28-a71c-08ffc1827947
		summarizeBy: none
		sourceColumn: date de publication

		variation Variation
			isDefault
			relationship: d694eb3c-63b4-4e09-a381-723a6a267157
			defaultHierarchy: LocalDateTable_179d40f8-346b-420c-9177-36a8c941aa0b.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column études
		dataType: string
		lineageTag: b13b6141-ec92-427e-8afc-575b0fec6516
		summarizeBy: none
		sourceColumn: études

		annotation SummarizationSetBy = Automatic

	column expérience
		dataType: string
		lineageTag: cc1417de-5336-4fac-9921-0a7cc3e0a961
		summarizeBy: none
		sourceColumn: expérience

		annotation SummarizationSetBy = Automatic

	column compétence
		dataType: string
		lineageTag: 48014cfd-22aa-4632-885a-77b253713bbc
		summarizeBy: none
		sourceColumn: compétence

		annotation SummarizationSetBy = Automatic

	column contrat
		dataType: string
		lineageTag: ea0b168a-ae88-44f9-9ae5-f50faae82abe
		summarizeBy: none
		sourceColumn: contrat

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: dd4655c6-851c-46d2-ae32-eb3e21ead10a
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column salaire
		dataType: string
		lineageTag: 03950c3e-1e78-4527-9432-98b154f5c7af
		summarizeBy: none
		sourceColumn: salaire

		annotation SummarizationSetBy = Automatic

	column source
		dataType: string
		lineageTag: 4a4181ed-8be0-4ca4-9dc9-c01e35fc8288
		summarizeBy: none
		sourceColumn: source

		annotation SummarizationSetBy = Automatic

	column 'lien offre'
		dataType: string
		lineageTag: d6bcec15-9d1e-4c3a-8935-f7d4bca76a4e
		summarizeBy: none
		sourceColumn: lien offre

		annotation SummarizationSetBy = Automatic

	column Année
		dataType: int64
		formatString: 0
		lineageTag: fbbd2702-d5a1-4a5b-80cc-febd757995db
		summarizeBy: sum
		sourceColumn: Année

		annotation SummarizationSetBy = Automatic

	column Mois
		dataType: int64
		formatString: 0
		lineageTag: c68397f2-d192-4930-ad3a-6415ce75e6e7
		summarizeBy: sum
		sourceColumn: Mois

		annotation SummarizationSetBy = Automatic

	partition merged_cm_jobs = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(CheminProjet & "\data\merged_cm_jobs_v2.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"poste", type text}, {"localité", type text}, {"organisation", type text}, {"date de publication", type date}, {"études", type text}, {"expérience", type text}, {"compétence", type text}, {"contrat", type text}, {"region", type text}, {"salaire", type text}, {"source", type text}, {"lien offre", type text}}),
				    #"Année insérée" = Table.AddColumn(#"Type modifié", "Année", each Date.Year([date de publication]), Int64.Type),
				    #"Mois inséré" = Table.AddColumn(#"Année insérée", "Mois", each Date.Month([date de publication]), Int64.Type),
				    #"Colonnes permutées" = Table.ReorderColumns(#"Mois inséré",{"poste", "localité", "organisation", "date de publication", "Année", "Mois", "études", "expérience", "compétence", "contrat", "region", "salaire", "source", "lien offre"})
				in
				    #"Colonnes permutées"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

